# .pre-commit-config.yaml

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
      - id: clang-format
        files: \.(cpp|h|c|cc|hpp)$  # Specify file extensions to format
